# Serve one applicant over HTTP. Nothing else.
#
#   docker build -t trust-issues-serving .
#   docker run --rm -p 8000:8000 trust-issues-serving
#
# The build REQUIRES models/lgbm_model.pkl and models/isotonic_calibrator.pkl
# in the build context. They are gitignored -- "regenerated by src/train.py,
# not source-controlled" -- so a fresh clone must run training before it can
# build this image. That is a real constraint, not an oversight: an image that
# silently shipped without a model would fail at the first request instead of
# at build time.
#
# data/ is excluded by .dockerignore and never enters the image.

FROM python:3.11-slim

# libgomp1 is LightGBM's OpenMP runtime. python:3.11-slim does not carry it,
# and without it `import lightgbm` dies with a bare
# "libgomp.so.1: cannot open shared object file" at startup -- after the image
# builds clean.
RUN apt-get update \
    && apt-get install -y --no-install-recommends libgomp1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

WORKDIR /app

# Dependencies before source, so an edit to serving/ does not re-resolve them.
# --frozen: fail if uv.lock disagrees with pyproject.toml, rather than quietly
# resolving something the lockfile never pinned.
# --no-install-project: this repo declares no build backend; it is imported off
# PYTHONPATH, not installed as a distribution.
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-install-project

COPY src/ ./src/
COPY serving/ ./serving/
COPY models/ ./models/

ENV PATH="/app/.venv/bin:$PATH" \
    PYTHONPATH=/app \
    PYTHONUNBUFFERED=1

# Nothing here needs to write to disk or bind a privileged port.
RUN useradd --create-home --uid 10001 appuser && chown -R appuser /app
USER appuser

EXPOSE 8000

# serving.app:app calls create_app() at import; lifespan then loads the
# artifacts and RAISES if they are missing, mismatched or stale. A container
# with a bad artifact exits non-zero at boot instead of serving 500s.
CMD ["uvicorn", "serving.app:app", "--host", "0.0.0.0", "--port", "8000"]
