# Serve one applicant over HTTP. Nothing else.
#
#   docker build -t trust-issues-serving .
#   docker run --rm -p 8000:8000 trust-issues-serving
#
# The build REQUIRES models/lgbm_model.pkl and models/isotonic_calibrator.pkl
# in the build context. They are gitignored -- "regenerated by src/train.py,
# not source-controlled" -- so a fresh clone must run training before it can
# build this image. That is a real constraint, not an oversight: an image that
# silently shipped without a model would fail at the first request instead of
# at build time.
#
# data/ is excluded by .dockerignore and never enters the image.

FROM python:3.11-slim

# libgomp1 is LightGBM's OpenMP runtime. python:3.11-slim does not carry it,
# and without it `import lightgbm` dies with a bare
# "libgomp.so.1: cannot open shared object file" at startup -- after the image
# builds clean.
RUN apt-get update \
    && apt-get install -y --no-install-recommends libgomp1 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

# Created before any COPY --chown= below needs it to exist. Nothing in this
# image needs to write to disk or bind a privileged port.
RUN useradd --create-home --uid 10001 appuser

WORKDIR /app

# Dependencies before source, so an edit to serving/ does not re-resolve them.
# --frozen: fail if uv.lock disagrees with pyproject.toml, rather than quietly
# resolving something the lockfile never pinned.
# --no-install-project: this repo declares no build backend; it is imported off
# PYTHONPATH, not installed as a distribution.
# --no-group training: mlflow/metaflow/matplotlib/seaborn are training/notebook
# dependencies serving's import graph never reaches (see pyproject.toml's
# dependencies comment for the verified per-package rationale) -- excluding
# them here is the entire point of the [dependency-groups] split. --no-dev
# drops pytest/jupyter/ipykernel, as before.
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev --no-group training --no-install-project

# --chown= sets ownership at copy time instead of a separate `chown -R`,
# which measured at ~885MB of duplicated layer content on this image's
# overlay2 storage driver (chown -R touches every file's metadata, forcing a
# copy-up of the entire preceding layer rather than a cheap in-place rewrite).
# appuser already exists (created above), so these can chown directly.
COPY --chown=appuser:appuser src/ ./src/
COPY --chown=appuser:appuser serving/ ./serving/
COPY --chown=appuser:appuser models/ ./models/

ENV PATH="/app/.venv/bin:$PATH" \
    PYTHONPATH=/app \
    PYTHONUNBUFFERED=1

USER appuser

EXPOSE 8000

# serving.app:app calls create_app() at import; lifespan then loads the
# artifacts and RAISES if they are missing, mismatched or stale. A container
# with a bad artifact exits non-zero at boot instead of serving 500s.
CMD ["uvicorn", "serving.app:app", "--host", "0.0.0.0", "--port", "8000"]
